/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class BoxTreeNodeRecord extends org.jooq.impl.UpdatableRecordImpl<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> {

	private static final long serialVersionUID = 168644611;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_PARENT_ID
	 * FOREIGN KEY (PARENT_ID, PARENT_ID)
	 * REFERENCES V1_0_0.BOX_TREE_NODE (ID)
	 * </pre></code>
	 */
	public void setParentId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.PARENT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_PARENT_ID
	 * FOREIGN KEY (PARENT_ID, PARENT_ID)
	 * REFERENCES V1_0_0.BOX_TREE_NODE (ID)
	 * </pre></code>
	 */
	public java.lang.Long getParentId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.PARENT_ID);
	}

	/**
	 * An uncommented item
	 */
	public void setName(java.lang.String value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.NAME, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getName() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.NAME);
	}

	/**
	 * An uncommented item
	 */
	public void setNodeType(java.lang.Integer value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.NODE_TYPE, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.Integer getNodeType() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.NODE_TYPE);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_TABLE_PROPERTY_ID
	 * FOREIGN KEY (TABLE_PROPERTY_ID)
	 * REFERENCES V1_0_0.TABLE_VIEW_PROPERTY (ID)
	 * </pre></code>
	 */
	public void setTablePropertyId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_TABLE_PROPERTY_ID
	 * FOREIGN KEY (TABLE_PROPERTY_ID)
	 * REFERENCES V1_0_0.TABLE_VIEW_PROPERTY (ID)
	 * </pre></code>
	 */
	public java.lang.Long getTablePropertyId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_TABLE_PROPERTY_ID
	 * FOREIGN KEY (TABLE_PROPERTY_ID)
	 * REFERENCES V1_0_0.TABLE_VIEW_PROPERTY (ID)
	 * </pre></code>
	 */
	public jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord fetchTableViewProperty() {
		return create()
			.selectFrom(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY)
			.where(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID.equal(getValue(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID)))
			.fetchOne();
	}

	/**
	 * Create a detached BoxTreeNodeRecord
	 */
	public BoxTreeNodeRecord() {
		super(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE);
	}
}
