/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class CollectionBoxItemRecord extends org.jooq.impl.UpdatableRecordImpl<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> {

	private static final long serialVersionUID = -644897536;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_EXHIBIT_ID
	 * FOREIGN KEY (EXHIBIT_ID)
	 * REFERENCES V1_0_0.MUSEUM_EXHIBIT (ID)
	 * </pre></code>
	 */
	public void setExhibitId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.EXHIBIT_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_EXHIBIT_ID
	 * FOREIGN KEY (EXHIBIT_ID)
	 * REFERENCES V1_0_0.MUSEUM_EXHIBIT (ID)
	 * </pre></code>
	 */
	public java.lang.Long getExhibitId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.EXHIBIT_ID);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_EXHIBIT_ID
	 * FOREIGN KEY (EXHIBIT_ID)
	 * REFERENCES V1_0_0.MUSEUM_EXHIBIT (ID)
	 * </pre></code>
	 */
	public jp.scid.genomemuseum.model.sql.tables.records.MuseumExhibitRecord fetchMuseumExhibit() {
		return create()
			.selectFrom(jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT)
			.where(jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT.ID.equal(getValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.EXHIBIT_ID)))
			.fetchOne();
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_BOX_ID
	 * FOREIGN KEY (BOX_ID, BOX_ID)
	 * REFERENCES V1_0_0.BOX_TREE_NODE (ID)
	 * </pre></code>
	 */
	public void setBoxId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.BOX_ID, value);
	}

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_BOX_ID
	 * FOREIGN KEY (BOX_ID, BOX_ID)
	 * REFERENCES V1_0_0.BOX_TREE_NODE (ID)
	 * </pre></code>
	 */
	public java.lang.Long getBoxId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.BOX_ID);
	}

	/**
	 * Create a detached CollectionBoxItemRecord
	 */
	public CollectionBoxItemRecord() {
		super(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM);
	}
}
