/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class TableViewPropertyRecord extends org.jooq.impl.UpdatableRecordImpl<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> {

	private static final long serialVersionUID = 669136746;

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID, value);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID);
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public java.util.List<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> fetchBoxTreeNodeList() {
		return create()
			.selectFrom(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE)
			.where(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID.equal(getValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID)))
			.fetch();
	}

	/**
	 * An uncommented item
	 */
	public void setVisibledColumns(java.lang.String value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.VISIBLED_COLUMNS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getVisibledColumns() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.VISIBLED_COLUMNS);
	}

	/**
	 * An uncommented item
	 */
	public void setOrderStatement(java.lang.String value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ORDER_STATEMENT, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getOrderStatement() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ORDER_STATEMENT);
	}

	/**
	 * An uncommented item
	 */
	public void setSelectedRows(java.lang.String value) {
		setValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.SELECTED_ROWS, value);
	}

	/**
	 * An uncommented item
	 */
	public java.lang.String getSelectedRows() {
		return getValue(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.SELECTED_ROWS);
	}

	/**
	 * Create a detached TableViewPropertyRecord
	 */
	public TableViewPropertyRecord() {
		super(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY);
	}
}
