-- デフォルト値
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN name SET DEFAULT '';

ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN sequence_length SET DEFAULT 0;

ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN accession SET DEFAULT '';

ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN namespace SET DEFAULT '';

ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN version SET DEFAULT 0;
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN definition SET DEFAULT '';
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN source_text SET DEFAULT '';
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN organism SET DEFAULT '';
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN sequence_unit SET DEFAULT 0;
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN molecule_type SET DEFAULT '';
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN file_type SET DEFAULT 0;
ALTER TABLE MUSEUM_EXHIBIT ALTER COLUMN file_uri SET DEFAULT '';
