/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the V1_0_0 schema
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
@SuppressWarnings({"unchecked"})
public class Keys extends org.jooq.impl.AbstractKeys {

	// IDENTITY definitions
	public static final org.jooq.Identity<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord, java.lang.Long> IDENTITY_BOX_TREE_NODE = createIdentity(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.ID);
	public static final org.jooq.Identity<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, java.lang.Long> IDENTITY_COLLECTION_BOX_ITEM = createIdentity(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.ID);
	public static final org.jooq.Identity<jp.scid.genomemuseum.model.sql.tables.records.MuseumExhibitRecord, java.lang.Long> IDENTITY_MUSEUM_EXHIBIT = createIdentity(jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT, jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT.ID);
	public static final org.jooq.Identity<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord, java.lang.Long> IDENTITY_TABLE_VIEW_PROPERTY = createIdentity(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY, jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID);

	// UNIQUE and PRIMARY KEY definitions
	public static final org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> CONSTRAINT_5D = createUniqueKey(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.ID);
	public static final org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> CONSTRAINT_5 = createUniqueKey(jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID);
	public static final org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> CONSTRAINT_4 = createUniqueKey(jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.ID);
	public static final org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.MuseumExhibitRecord> CONSTRAINT_D = createUniqueKey(jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT, jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT.ID);
	public static final org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> CONSTRAINT_A = createUniqueKey(jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY, jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY.ID);

	// FOREIGN KEY definitions
	public static final org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord, jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> FK_BOX_PARENT_ID = createForeignKey(CONSTRAINT_5D, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.PARENT_ID, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.PARENT_ID);
	public static final org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord, jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> FK_BOX_TABLE_PROPERTY_ID = createForeignKey(CONSTRAINT_A, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE, jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE.TABLE_PROPERTY_ID);
	public static final org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, jp.scid.genomemuseum.model.sql.tables.records.MuseumExhibitRecord> FK_BOX_ITEM_EXHIBIT_ID = createForeignKey(CONSTRAINT_D, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.EXHIBIT_ID);
	public static final org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, jp.scid.genomemuseum.model.sql.tables.records.BoxTreeNodeRecord> FK_BOX_ITEM_BOX_ID = createForeignKey(CONSTRAINT_5D, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.BOX_ID, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM.BOX_ID);

	/**
	 * No instances
	 */
	private Keys() {}
}
