/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in V1_0_0
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public final class Sequences {

	/**
	 * The sequence V1_0_0.SEQ_BOX_TREE_NODE
	 */
	public static final org.jooq.Sequence<java.lang.Long> SEQ_BOX_TREE_NODE = new org.jooq.impl.SequenceImpl<java.lang.Long>("SEQ_BOX_TREE_NODE", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SEQ_COLLECTIN_BOX_ITEM
	 */
	public static final org.jooq.Sequence<java.lang.Long> SEQ_COLLECTIN_BOX_ITEM = new org.jooq.impl.SequenceImpl<java.lang.Long>("SEQ_COLLECTIN_BOX_ITEM", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SEQ_MUSEUM_EXHIBIT
	 */
	public static final org.jooq.Sequence<java.lang.Long> SEQ_MUSEUM_EXHIBIT = new org.jooq.impl.SequenceImpl<java.lang.Long>("SEQ_MUSEUM_EXHIBIT", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SEQ_TABLE_VIEW_PROPERTY
	 */
	public static final org.jooq.Sequence<java.lang.Long> SEQ_TABLE_VIEW_PROPERTY = new org.jooq.impl.SequenceImpl<java.lang.Long>("SEQ_TABLE_VIEW_PROPERTY", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SYSTEM_SEQUENCE_0D69970C_AF8C_41D2_A1DF_F79712560022
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_0D69970C_AF8C_41D2_A1DF_F79712560022 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_0D69970C_AF8C_41D2_A1DF_F79712560022", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SYSTEM_SEQUENCE_2BFDFD6C_6CA7_4E55_B1B9_22175D26C472
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_2BFDFD6C_6CA7_4E55_B1B9_22175D26C472 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_2BFDFD6C_6CA7_4E55_B1B9_22175D26C472", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SYSTEM_SEQUENCE_92472A51_4C68_45E6_819A_109DBD5439F6
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_92472A51_4C68_45E6_819A_109DBD5439F6 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_92472A51_4C68_45E6_819A_109DBD5439F6", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence V1_0_0.SYSTEM_SEQUENCE_C60A34ED_D2ED_4F60_A603_947E18E3FDE6
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_C60A34ED_D2ED_4F60_A603_947E18E3FDE6 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_C60A34ED_D2ED_4F60_A603_947E18E3FDE6", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * No instances
	 */
	private Sequences() {}
}
