/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in V1_0_0
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public final class Tables {

	/**
	 * The table V1_0_0.BOX_TREE_NODE
	 */
	public static jp.scid.genomemuseum.model.sql.tables.BoxTreeNode BOX_TREE_NODE = jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE;

	/**
	 * The table V1_0_0.COLLECTION_BOX_ITEM
	 */
	public static jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem COLLECTION_BOX_ITEM = jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM;

	/**
	 * The table V1_0_0.MUSEUM_EXHIBIT
	 */
	public static jp.scid.genomemuseum.model.sql.tables.MuseumExhibit MUSEUM_EXHIBIT = jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT;

	/**
	 * The table V1_0_0.TABLE_VIEW_PROPERTY
	 */
	public static jp.scid.genomemuseum.model.sql.tables.TableViewProperty TABLE_VIEW_PROPERTY = jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY;

	/**
	 * No instances
	 */
	private Tables() {}
}
