/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class V1_0_0Factory extends org.jooq.util.h2.H2Factory {

	private static final long serialVersionUID = -2017145954;

	/**
	 * Create a factory with a connection
	 *
	 * @param connection The connection to use with objects created from this factory
	 */
	public V1_0_0Factory(java.sql.Connection connection) {
		super(connection);
	}

	/**
	 * Create a factory with a connection and a schema mapping
	 * 
	 * @deprecated - 2.0.5 - Use {@link #V1_0_0Factory(java.sql.Connection, org.jooq.conf.Settings)} instead
	 */
	@Deprecated
	public V1_0_0Factory(java.sql.Connection connection, org.jooq.SchemaMapping mapping) {
		super(connection, mapping);
	}

	/**
	 * Create a factory with a connection and some settings
	 *
	 * @param connection The connection to use with objects created from this factory
	 * @param settings The settings to apply to objects created from this factory
	 */
	public V1_0_0Factory(java.sql.Connection connection, org.jooq.conf.Settings settings) {
		super(connection, settings);
	}
}
