/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class V1_0_0 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 707196870;

	/**
	 * The singleton instance of V1_0_0
	 */
	public static final V1_0_0 V1_0_0 = new V1_0_0();

	/**
	 * No further instances allowed
	 */
	private V1_0_0() {
		super("V1_0_0");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE,
			jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM,
			jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT,
			jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY);
	}
}
