/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class V1_0_0 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 213168759;

	/**
	 * The singleton instance of V1_0_0
	 */
	public static final V1_0_0 V1_0_0 = new V1_0_0();

	/**
	 * No further instances allowed
	 */
	private V1_0_0() {
		super("V1_0_0");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			jp.scid.genomemuseum.model.sql.Sequences.SEQ_BOX_TREE_NODE,
			jp.scid.genomemuseum.model.sql.Sequences.SEQ_COLLECTIN_BOX_ITEM,
			jp.scid.genomemuseum.model.sql.Sequences.SEQ_MUSEUM_EXHIBIT,
			jp.scid.genomemuseum.model.sql.Sequences.SEQ_TABLE_VIEW_PROPERTY,
			jp.scid.genomemuseum.model.sql.Sequences.SYSTEM_SEQUENCE_0D69970C_AF8C_41D2_A1DF_F79712560022,
			jp.scid.genomemuseum.model.sql.Sequences.SYSTEM_SEQUENCE_2BFDFD6C_6CA7_4E55_B1B9_22175D26C472,
			jp.scid.genomemuseum.model.sql.Sequences.SYSTEM_SEQUENCE_92472A51_4C68_45E6_819A_109DBD5439F6,
			jp.scid.genomemuseum.model.sql.Sequences.SYSTEM_SEQUENCE_C60A34ED_D2ED_4F60_A603_947E18E3FDE6);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			jp.scid.genomemuseum.model.sql.tables.BoxTreeNode.BOX_TREE_NODE,
			jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM,
			jp.scid.genomemuseum.model.sql.tables.MuseumExhibit.MUSEUM_EXHIBIT,
			jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY);
	}
}
