/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class CollectionBoxItem extends org.jooq.impl.UpdatableTableImpl<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> {

	private static final long serialVersionUID = -344063057;

	/**
	 * The singleton instance of V1_0_0.COLLECTION_BOX_ITEM
	 */
	public static final jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem COLLECTION_BOX_ITEM = new jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> __RECORD_TYPE = jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_EXHIBIT_ID
	 * FOREIGN KEY (EXHIBIT_ID)
	 * REFERENCES V1_0_0.MUSEUM_EXHIBIT (ID)
	 * </pre></code>
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, java.lang.Long> EXHIBIT_ID = createField("EXHIBIT_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * An uncommented item
	 * <p>
	 * <code><pre>
	 * CONSTRAINT FK_BOX_ITEM_BOX_ID
	 * FOREIGN KEY (BOX_ID, BOX_ID)
	 * REFERENCES V1_0_0.BOX_TREE_NODE (ID)
	 * </pre></code>
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, java.lang.Long> BOX_ID = createField("BOX_ID", org.jooq.impl.SQLDataType.BIGINT, this);

	public CollectionBoxItem() {
		super("COLLECTION_BOX_ITEM", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0);
	}

	public CollectionBoxItem(java.lang.String alias) {
		super(alias, jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem.COLLECTION_BOX_ITEM);
	}

	@Override
	public org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord> getMainKey() {
		return jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_4D;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord>>asList(jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_4D, jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_4);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<jp.scid.genomemuseum.model.sql.tables.records.CollectionBoxItemRecord, ?>>asList(jp.scid.genomemuseum.model.sql.Keys.FK_BOX_ITEM_EXHIBIT_ID, jp.scid.genomemuseum.model.sql.Keys.FK_BOX_ITEM_BOX_ID);
	}

	@Override
	public jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem as(java.lang.String alias) {
		return new jp.scid.genomemuseum.model.sql.tables.CollectionBoxItem(alias);
	}
}
