/**
 * This class is generated by jOOQ
 */
package jp.scid.genomemuseum.model.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.2.0"},
                            comments = "This class is generated by jOOQ")
public class TableViewProperty extends org.jooq.impl.UpdatableTableImpl<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> {

	private static final long serialVersionUID = 644829589;

	/**
	 * The singleton instance of V1_0_0.TABLE_VIEW_PROPERTY
	 */
	public static final jp.scid.genomemuseum.model.sql.tables.TableViewProperty TABLE_VIEW_PROPERTY = new jp.scid.genomemuseum.model.sql.tables.TableViewProperty();

	/**
	 * The class holding records for this type
	 */
	private static final java.lang.Class<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> __RECORD_TYPE = jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord.class;

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> getRecordType() {
		return __RECORD_TYPE;
	}

	/**
	 * An uncommented item
	 * 
	 * PRIMARY KEY
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord, java.lang.String> VISIBLED_COLUMNS = createField("VISIBLED_COLUMNS", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord, java.lang.String> ORDER_STATEMENT = createField("ORDER_STATEMENT", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * An uncommented item
	 */
	public final org.jooq.TableField<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord, java.lang.String> SELECTED_ROWS = createField("SELECTED_ROWS", org.jooq.impl.SQLDataType.VARCHAR, this);

	public TableViewProperty() {
		super("TABLE_VIEW_PROPERTY", jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0);
	}

	public TableViewProperty(java.lang.String alias) {
		super(alias, jp.scid.genomemuseum.model.sql.V1_0_0.V1_0_0, jp.scid.genomemuseum.model.sql.tables.TableViewProperty.TABLE_VIEW_PROPERTY);
	}

	@Override
	public org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord> getMainKey() {
		return jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_A2;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<jp.scid.genomemuseum.model.sql.tables.records.TableViewPropertyRecord>>asList(jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_A2, jp.scid.genomemuseum.model.sql.Keys.CONSTRAINT_A);
	}

	@Override
	public jp.scid.genomemuseum.model.sql.tables.TableViewProperty as(java.lang.String alias) {
		return new jp.scid.genomemuseum.model.sql.tables.TableViewProperty(alias);
	}
}
